AWSTemplateFormatVersion: "2010-09-09"
Description: Mekong IAM Definition
Parameters:
  S3ResourceTempBucket:
    Type: String
    Description: AWS S3 Temporary Bucket Name
    Default: mekong-temp
Resources:
  # Policies
  StoreLocationProjectS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grant Read & Write Access to S3 Bucket for StoreLocation Project
      ManagedPolicyName: StoreLocationS3Access
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObjectAcl
            Resource:
              - !Sub 'arn:aws:s3:::${S3ResourceTempBucket}'
              - !Sub 'arn:aws:s3:::${S3ResourceTempBucket}/*'

  # Users
  MapperUser:
    Type: AWS::IAM::User
    Description: StoreLocation Project AWS User
    Properties:
      UserName: mapper
      ManagedPolicyArns:
      - !Ref StoreLocationProjectS3Policy